name: Code Update CI
on:
  push:
    branches: [ master ]
    paths: [ 'code/**', '.github/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: neo4j-contrib/sandbox-code-updater
          event-type: template-code-changes
          client-payload: '{"source": "${{ github.repository }}", "commit": "${{ github.sha }}"}'
